Repository nutanix/terraform-provider-nutanix, pull requests merged in 2020-04, with the labels that each got.

#107 added nil checking for deviceProperties
  nutanix/categories_schema_migrate.go
  nutanix/categories_schema_migrate_test.go
  nutanix/data_source_nutanix_cluster.go
  nutanix/data_source_nutanix_clusters.go
  nutanix/data_source_nutanix_image.go
  nutanix/data_source_nutanix_network_security_rule.go
  nutanix/data_source_nutanix_subnet.go
  nutanix/data_source_nutanix_virtual_machine.go
  nutanix/resource_nutanix_image.go
  nutanix/resource_nutanix_network_security_rule.go
  nutanix/resource_nutanix_subnet.go
  nutanix/resource_nutanix_virtual_machine.go
Labels: size/XXL

#80 Add missing API fields for structs
  client/v3/v3_structs.go
Labels: size/XS

#111 Bugfix/cloudinit final
  go.mod
  nutanix/categories_schema_migrate.go
  nutanix/categories_schema_migrate_test.go
  nutanix/data_source_nutanix_cluster.go
  nutanix/data_source_nutanix_clusters.go
  nutanix/data_source_nutanix_image.go
  nutanix/data_source_nutanix_network_security_rule.go
  nutanix/data_source_nutanix_subnet.go
  nutanix/data_source_nutanix_virtual_machine.go
  nutanix/resource_nutanix_image.go
  nutanix/resource_nutanix_network_security_rule.go
  nutanix/resource_nutanix_subnet.go
  nutanix/resource_nutanix_virtual_machine.go
  nutanix/resource_nutanix_virtual_machine_test.go
  nutanix/structure.go
Labels: size/XXL

#116 Fix #70: Added Host datasources
  client/v3/v3_service.go
  client/v3/v3_service_test.go
  client/v3/v3_structs.go
  go.mod
  go.sum
  nutanix/data_source_nutanix_host.go
  nutanix/data_source_nutanix_host_test.go
  nutanix/data_source_nutanix_hosts.go
  nutanix/data_source_nutanix_hosts_test.go
  nutanix/provider.go
  vendor/github.com/spf13/cast/.travis.yml
  vendor/github.com/spf13/cast/Makefile
  vendor/github.com/spf13/cast/caste.go
  vendor/modules.txt
Labels: dependencies, size/XXL
