Repository nutanix/terraform-provider-nutanix, pull requests merged in 2020-05, with the labels that each got.

#85 website: # removed
  website/nutanix.erb
Labels: documentation, size/XS

#88 implement session based authentification
  client/client.go
  client/client_test.go
  nutanix/config.go
  nutanix/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#120 fix for issue #119 - timeout issue and categories reboot
  nutanix/resource_nutanix_virtual_machine.go
Labels: size/XS

#92 Reduce the amount of API requests and improvements
  client/v3/v3_service.go
  client/v3/v3_service_test.go
  client/v3/v3_structs.go
  nutanix/data_source_nutanix_clusters.go
  nutanix/data_source_nutanix_image.go
  nutanix/data_source_nutanix_subnet.go
  nutanix/resource_nutanix_image.go
  nutanix/resource_nutanix_network_security_rule.go
  nutanix/resource_nutanix_subnet.go
  nutanix/resource_nutanix_virtual_machine.go
Labels: size/M

#114 Fix #35: Validated the terraform configuration
  .gitignore
  nutanix/resource_nutanix_virtual_machine_test.go
Labels: size/XL

#122 fix: added validation to avoid nil pointer error
  nutanix/resource_nutanix_subnet.go
Labels: size/XS

#129 Fix for #128 Changed parameter for subnet filter
  nutanix/data_source_nutanix_subnet.go
Labels: size/XS

#127 fix issue #126
  nutanix/data_source_nutanix_network_security_rule.go
  nutanix/data_source_nutanix_network_security_rule_test.go
  nutanix/resource_nutanix_network_security_rule.go
Labels: size/L

#115 Fix #73 Added datasource of subnets
  go.sum
  nutanix/data_source_nutanix_subnets.go
  nutanix/data_source_nutanix_subnets_test.go
  nutanix/provider.go
Labels: size/XL

#81 Add support for mapstructure decode tag for reusability
  .golangci.yml
  client/v3/v3_structs.go
  go.mod
  go.sum
Labels: size/XXL
