Repository nutanix/terraform-provider-nutanix, pull requests merged in 2020-06, with the labels that each got.

#133 docs: added more info about Sysprep for install type
  website/docs/d/virtual_machine.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#136 Added new parameter for VM use_hot_add
  go.mod
  go.sum
  nutanix/resource_nutanix_virtual_machine.go
  nutanix/resource_nutanix_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/M

#134 fix #112: Improve error handling on incorrect API calls
  client/client.go
Labels: size/XS

#139 Docs for datasource of host(s)
  website/docs/d/host.html.markdown
  website/docs/d/hosts.html.markdown
Labels: documentation, size/L

#140 Updated docs and attributes for test client
  client/v3/v3_service_test.go
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/d/image.html.markdown
  website/docs/d/network_security_rule.html.markdown
  website/docs/d/project.html.markdown
  website/docs/d/projects.html.markdown
  website/docs/d/subnet.html.markdown
  website/docs/d/virtual_machine.html.markdown
  website/docs/d/volume_group.html.markdown
  website/docs/r/image.html.markdown
  website/docs/r/network_security_rule.html.markdown
  website/docs/r/project.markdown
  website/docs/r/subnet.html.markdown
  website/docs/r/virtual_machine.html.markdown
  website/docs/r/volume_group.html.markdown
Labels: documentation, size/S

#144 fix issue 143: …
  nutanix/resource_nutanix_virtual_machine.go
Labels: size/XS

#138 Fix #78: Cannot specify target container when adding disks to a virtual machine resource
  client/v3/v3_structs.go
  nutanix/data_source_nutanix_virtual_machine.go
  nutanix/data_source_nutanix_virtual_machine_test.go
  nutanix/resource_nutanix_virtual_machine.go
  nutanix/resource_nutanix_virtual_machine_test.go
  nutanix/structure.go
  website/docs/d/virtual_machine.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XL

#137 fix #130: Resize disk on clone
  nutanix/resource_nutanix_virtual_machine.go
  nutanix/resource_nutanix_virtual_machine_test.go
Labels: documentation, size/M

#146 Disabled project resource, tests fixed and issue fixed
  nutanix/data_source_nutanix_host_test.go
  nutanix/data_source_nutanix_project.future
  nutanix/data_source_nutanix_project_test.future
  nutanix/data_source_nutanix_projects.future
  nutanix/data_source_nutanix_projects_test.future
  nutanix/provider.go
  nutanix/resource_nutanix_image_test.go
  nutanix/resource_nutanix_network_security_rule_test.go
  nutanix/resource_nutanix_project.future
  nutanix/resource_nutanix_project_test.future
  nutanix/resource_nutanix_subnet_test.go
  nutanix/resource_nutanix_virtual_machine.go
  nutanix/resource_nutanix_virtual_machine_test.go
Labels: size/S
