Repository nutanix/terraform-provider-nutanix, pull requests merged in 2020-03, with the labels that each got.

#100 Feature/cluster datasource name
  nutanix/data_source_nutanix_cluster.go
  nutanix/data_source_nutanix_cluster_test.go
  nutanix/resource_nutanix_virtual_machine.go
  nutanix/resource_nutanix_virtual_machine_test.go
Labels: size/L

#102 Fix for issue 58
  nutanix/resource_nutanix_virtual_machine.go
  nutanix/resource_nutanix_virtual_machine_test.go
  utils/utils.go
Labels: size/M

#103 Added preCheck function to verify that env variables were set
  nutanix/provider_test.go
Labels: size/XS

#106 bugfix device_properties in a disk_list
  nutanix/resource_nutanix_virtual_machine.go
  nutanix/resource_nutanix_virtual_machine_test.go
Labels: size/M
